#!/bin/bash
# Generate Homebrew/Scoop/Chocolatey manifests for jbcom/pkgs.
#
# Usage: generate_pkg_manifests.sh VERSION CHECKSUMS_FILE OUT_DIR
#
# CHECKSUMS_FILE is the release's checksums.txt (one `<sha256>  <name>` line
# per tarball/zip). Values are read by grep; no fallback on missing
# entries — failing loud is correct.
#
# Produces in OUT_DIR:
#   paranoid-passwd.rb          (Homebrew formula; linux+darwin × amd64+arm64)
#   paranoid-passwd.json        (Scoop manifest; windows/amd64)
#   paranoid-passwd.nuspec      (Chocolatey nuspec)
#   chocolateyInstall.ps1       (Chocolatey install script)
#   VERIFICATION.txt            (Chocolatey verification doc)

set -euo pipefail

VERSION="${1:?version required}"
CHECKSUMS="${2:?checksums file required}"
OUT="${3:?output dir required}"

mkdir -p "${OUT}"

REPO="jbcom/paranoid-passwd"
TAG="paranoid-passwd-v${VERSION}"
REL_URL="https://github.com/${REPO}/releases/download/${TAG}"

# Pull a SHA-256 for a given asset name.
sha_of() {
    local name="$1"
    local sha
    sha=$(grep " ${name}\$" "${CHECKSUMS}" | awk '{print $1}')
    if [ -z "${sha}" ]; then
        echo "FATAL: no checksum for ${name} in ${CHECKSUMS}" >&2
        exit 1
    fi
    printf '%s' "${sha}"
}

LINUX_AMD64="paranoid-passwd-${VERSION}-linux-amd64.tar.gz"
LINUX_ARM64="paranoid-passwd-${VERSION}-linux-arm64.tar.gz"
DARWIN_AMD64="paranoid-passwd-${VERSION}-darwin-amd64.tar.gz"
DARWIN_ARM64="paranoid-passwd-${VERSION}-darwin-arm64.tar.gz"
WIN_AMD64="paranoid-passwd-${VERSION}-windows-amd64.zip"

SHA_LINUX_AMD64=$(sha_of "${LINUX_AMD64}")
SHA_LINUX_ARM64=$(sha_of "${LINUX_ARM64}")
SHA_DARWIN_AMD64=$(sha_of "${DARWIN_AMD64}")
SHA_DARWIN_ARM64=$(sha_of "${DARWIN_ARM64}")
SHA_WIN_AMD64=$(sha_of "${WIN_AMD64}")

# ── Homebrew ────────────────────────────────────────────────────
cat > "${OUT}/paranoid-passwd.rb" <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by paranoid-passwd's release pipeline.
# DO NOT EDIT.
class ParanoidPasswd < Formula
  desc "Rust-native self-auditing password generator with CLI and TUI"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${REL_URL}/${DARWIN_ARM64}"
      sha256 "${SHA_DARWIN_ARM64}"
    end
    if Hardware::CPU.intel?
      url "${REL_URL}/${DARWIN_AMD64}"
      sha256 "${SHA_DARWIN_AMD64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${REL_URL}/${LINUX_ARM64}"
      sha256 "${SHA_LINUX_ARM64}"
    end
    if Hardware::CPU.intel?
      url "${REL_URL}/${LINUX_AMD64}"
      sha256 "${SHA_LINUX_AMD64}"
    end
  end

  def install
    bin.install "paranoid-passwd"
  end

  test do
    system "#{bin}/paranoid-passwd", "--version"
  end
end
EOF

# ── Scoop ───────────────────────────────────────────────────────
cat > "${OUT}/paranoid-passwd.json" <<EOF
{
  "version": "${VERSION}",
  "description": "Rust-native self-auditing password generator with CLI and TUI",
  "homepage": "https://github.com/${REPO}",
  "license": "MIT",
  "url": "${REL_URL}/${WIN_AMD64}",
  "hash": "${SHA_WIN_AMD64}",
  "bin": "paranoid-passwd.exe",
  "architecture": {
    "64bit": {
      "url": "${REL_URL}/${WIN_AMD64}",
      "hash": "${SHA_WIN_AMD64}"
    }
  },
  "checkver": {
    "github": "https://github.com/${REPO}"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/${REPO}/releases/download/paranoid-passwd-v\$version/paranoid-passwd-\$version-windows-amd64.zip"
      }
    }
  }
}
EOF

# ── Chocolatey ──────────────────────────────────────────────────
cat > "${OUT}/paranoid-passwd.nuspec" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>paranoid-passwd</id>
    <version>${VERSION}</version>
    <title>Paranoid Password Generator</title>
    <authors>Jon B</authors>
    <owners>jbcom</owners>
    <projectUrl>https://github.com/${REPO}</projectUrl>
    <licenseUrl>https://github.com/${REPO}/blob/main/LICENSE</licenseUrl>
    <projectSourceUrl>https://github.com/${REPO}</projectSourceUrl>
    <packageSourceUrl>https://github.com/jbcom/pkgs</packageSourceUrl>
    <docsUrl>https://github.com/${REPO}#readme</docsUrl>
    <bugTrackerUrl>https://github.com/${REPO}/issues</bugTrackerUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <summary>Rust-native self-auditing password generator with CLI and TUI</summary>
    <description>
Paranoid-passwd generates passwords using a native Rust core that audits
itself on every run: chi-squared uniformity, serial correlation,
collision detection, entropy proof, compliance policy evaluation,
and weak-pattern detection before emitting output.
    </description>
    <tags>password security cli tui rust paranoid</tags>
    <releaseNotes>https://github.com/${REPO}/releases/tag/${TAG}</releaseNotes>
  </metadata>
  <files>
    <file src="tools/**" target="tools" />
  </files>
</package>
EOF

cat > "${OUT}/chocolateyInstall.ps1" <<EOF
\$ErrorActionPreference = 'Stop'
\$packageName  = 'paranoid-passwd'
\$toolsDir     = "\$(Split-Path -parent \$MyInvocation.MyCommand.Definition)"
\$url64        = '${REL_URL}/${WIN_AMD64}'
\$checksum64   = '${SHA_WIN_AMD64}'

\$packageArgs = @{
  packageName   = \$packageName
  unzipLocation = \$toolsDir
  url64bit      = \$url64
  checksum64    = \$checksum64
  checksumType64= 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
EOF

cat > "${OUT}/VERIFICATION.txt" <<EOF
VERIFICATION

paranoid-passwd ${VERSION} for Windows amd64 ships as a ZIP archive at:
  ${REL_URL}/${WIN_AMD64}

Checksum (SHA-256): ${SHA_WIN_AMD64}

Verify locally on Windows:

  Get-FileHash paranoid-passwd-${VERSION}-windows-amd64.zip -Algorithm SHA256

Also verify sigstore build provenance:

  gh attestation verify paranoid-passwd-${VERSION}-windows-amd64.zip --owner jbcom

Source: https://github.com/${REPO}
EOF

echo "Generated manifests in ${OUT}:"
ls -la "${OUT}/"
