# ================================================================
# cmake/wasm32-wasi.cmake — Zig cross-compilation toolchain
#
# Configures CMake to use Zig as a C-to-WASM cross-compiler
# targeting wasm32-wasi. Zig bundles its own WASI libc and sysroot,
# so no external SDK is needed.
#
# Usage:
#   cmake -B build/wasm \
#       -DCMAKE_TOOLCHAIN_FILE=cmake/wasm32-wasi.cmake \
#       -DCMAKE_BUILD_TYPE=Release
#   cmake --build build/wasm
#
# Prerequisites:
#   - Zig >= 0.13.0 (brew install zig / apk add zig / snap install zig)
#   - vendor/openssl/lib/libcrypto.a (built from source for wasm32-wasi)
#
# How this works:
#   Zig provides a `zig cc` mode that acts as a drop-in replacement
#   for gcc/clang. It accepts -target flags to cross-compile for any
#   supported triple. For wasm32-wasi:
#     zig cc -target wasm32-wasi -o output.wasm input.c
#
#   CMake does not natively support `zig cc` as a two-word compiler
#   command. We use a wrapper script (cmake/zig-cc.sh) to handle this.
#   The wrapper script simply invokes `zig cc` with the -target flag
#   prepended to all arguments.
#
# Alternatives considered:
#   - CMAKE_C_COMPILER_ARG1: Does not work reliably with CMake's
#     compiler identification step (try_compile fails).
#   - CMAKE_C_COMPILER_LAUNCHER: Designed for ccache/distcc, not for
#     prepending subcommands. Breaks link steps.
#   - Setting CMAKE_C_COMPILER to "zig" with extra flags: Zig's main
#     binary is not a C compiler -- `zig cc` is the C compiler mode.
#
# The wrapper script approach is used by the Zig community and
# documented in Zig's wiki for CMake integration.
# ================================================================

# ── System identification ────────────────────────────────────
set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

# ── Locate Zig ───────────────────────────────────────────────
find_program(ZIG_EXECUTABLE zig REQUIRED)
message(STATUS "Found Zig: ${ZIG_EXECUTABLE}")

# ── Create wrapper scripts at configure time ─────────────────
# CMake needs a single executable as CMAKE_C_COMPILER. Zig's C
# compiler is invoked as `zig cc`, which is two words. We generate
# thin shell wrappers that CMake can point to as the compiler and
# linker commands.
#
# The wrappers:
#   1. Invoke `zig cc` with `-target wasm32-wasi`
#   2. Pass through all arguments from CMake
#   3. Are created in the build directory (not checked into source)

set(ZIG_CC_WRAPPER "${CMAKE_CURRENT_BINARY_DIR}/zig-cc-wasm32-wasi")

# Write the wrapper script. file(WRITE) runs at configure time.
# -mexec-model=reactor tells the WASI runtime this is a reactor
# (library) module, not a command. Without this flag, Zig >= 0.14
# links __main_void.o from libc which requires a main() symbol,
# breaking --no-entry reactor builds. This flag is supported by
# Zig >= 0.13.0 and harmless on older versions.
file(WRITE "${ZIG_CC_WRAPPER}" "#!/bin/sh
# Auto-generated by cmake/wasm32-wasi.cmake -- do not edit
exec \"${ZIG_EXECUTABLE}\" cc -target wasm32-wasi -mexec-model=reactor \"$@\"
")

# Make the wrapper executable
execute_process(
    COMMAND chmod +x "${ZIG_CC_WRAPPER}"
)

# ── Compiler configuration ───────────────────────────────────
set(CMAKE_C_COMPILER "${ZIG_CC_WRAPPER}")

# Tell CMake this is a Clang-compatible compiler (Zig's cc is
# Clang-based). This prevents CMake from running compiler
# identification tests that would fail due to the WASM target.
set(CMAKE_C_COMPILER_ID "Clang")
set(CMAKE_C_COMPILER_FORCED TRUE)

# ── Optimization flags ───────────────────────────────────────
set(CMAKE_C_FLAGS_RELEASE "-O2" CACHE STRING "Release flags" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "RelWithDebInfo flags" FORCE)
set(CMAKE_C_FLAGS_MINSIZEREL "-Os" CACHE STRING "MinSizeRel flags" FORCE)
set(CMAKE_C_FLAGS_DEBUG "-O0 -g" CACHE STRING "Debug flags" FORCE)

# ── Linker configuration ────────────────────────────────────
# Zig handles linking internally. The same wrapper is used for
# linking since `zig cc` handles both compile and link steps.
#
set(CMAKE_C_LINK_EXECUTABLE
    "${ZIG_CC_WRAPPER} <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)

# ── Output configuration ────────────────────────────────────
# WASM files have .wasm extension, not the host platform default.
set(CMAKE_EXECUTABLE_SUFFIX ".wasm" CACHE STRING "" FORCE)

# WASM targets are always static -- no shared libraries.
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

# ── Cross-compilation search paths ──────────────────────────
# Zig handles the sysroot internally for WASI targets.
# Tell CMake not to search host paths for libraries/includes.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# ── Static library archiver ─────────────────────────────────
# If any static libraries need to be created during the build,
# use Zig's ar mode.
set(ZIG_AR_WRAPPER "${CMAKE_CURRENT_BINARY_DIR}/zig-ar-wasm32-wasi")

file(WRITE "${ZIG_AR_WRAPPER}" "#!/bin/sh
# Auto-generated by cmake/wasm32-wasi.cmake -- do not edit
exec \"${ZIG_EXECUTABLE}\" ar \"$@\"
")

execute_process(
    COMMAND chmod +x "${ZIG_AR_WRAPPER}"
)

set(CMAKE_AR "${ZIG_AR_WRAPPER}" CACHE FILEPATH "Archiver" FORCE)
set(CMAKE_RANLIB "true" CACHE FILEPATH "Ranlib (no-op for Zig)" FORCE)
