# ================================================================
# cmake/zig-cross.cmake — Zig cross-compilation toolchain for the CLI
#
# Mirrors the wrapper-script pattern of cmake/wasm32-wasi.cmake.
# CMake cannot reliably invoke `zig cc -target ...` via
# CMAKE_C_COMPILER_ARG1, so we generate thin wrapper scripts at
# configure time and point CMAKE_C_COMPILER / CMAKE_AR at them.
#
# Use:
#   cmake -B build/cli-linux-amd64 \
#       -DCMAKE_TOOLCHAIN_FILE=cmake/zig-cross.cmake \
#       -DPARANOID_TARGET=x86_64-linux-musl \
#       -DCMAKE_BUILD_TYPE=Release
#   cmake --build build/cli-linux-amd64 --target paranoid_cli
#
# Supported PARANOID_TARGET values:
#   x86_64-linux-musl    (static Linux amd64)
#   aarch64-linux-musl   (static Linux arm64)
#   x86_64-macos-none    (macOS Intel, libSystem dynamic)
#   aarch64-macos-none   (macOS Apple Silicon, libSystem dynamic)
# ================================================================

if(NOT DEFINED PARANOID_TARGET)
    message(FATAL_ERROR "zig-cross.cmake requires -DPARANOID_TARGET=<triple>")
endif()

# ── System identification ────────────────────────────────────
if(PARANOID_TARGET MATCHES "linux")
    set(CMAKE_SYSTEM_NAME Linux)
    set(PARANOID_LINKER_GC "-Wl,--gc-sections")
elseif(PARANOID_TARGET MATCHES "macos")
    set(CMAKE_SYSTEM_NAME Darwin)
    # ld64 / lld-darwin uses -dead_strip, not --gc-sections.
    set(PARANOID_LINKER_GC "-Wl,-dead_strip")
elseif(PARANOID_TARGET MATCHES "windows")
    set(CMAKE_SYSTEM_NAME Windows)
    set(PARANOID_LINKER_GC "")
else()
    message(FATAL_ERROR "Unknown PARANOID_TARGET: ${PARANOID_TARGET}")
endif()

if(PARANOID_TARGET MATCHES "^x86_64")
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
elseif(PARANOID_TARGET MATCHES "^aarch64")
    set(CMAKE_SYSTEM_PROCESSOR aarch64)
endif()

set(CMAKE_CROSSCOMPILING TRUE)

# ── Locate Zig ───────────────────────────────────────────────
find_program(ZIG_EXECUTABLE zig REQUIRED)
message(STATUS "Found Zig: ${ZIG_EXECUTABLE}")
message(STATUS "Cross-compiling to: ${PARANOID_TARGET}")

# ── Wrapper scripts at configure time ────────────────────────
# Same approach as cmake/wasm32-wasi.cmake — CMake needs a single
# executable for CMAKE_C_COMPILER, but `zig cc` is two words. Generate
# thin shell wrappers in the build directory.
set(ZIG_CC_WRAPPER "${CMAKE_CURRENT_BINARY_DIR}/zig-cc-${PARANOID_TARGET}")
set(ZIG_AR_WRAPPER "${CMAKE_CURRENT_BINARY_DIR}/zig-ar-${PARANOID_TARGET}")

file(WRITE "${ZIG_CC_WRAPPER}" "#!/bin/sh
# Auto-generated by cmake/zig-cross.cmake -- do not edit
exec \"${ZIG_EXECUTABLE}\" cc -target ${PARANOID_TARGET} \"$@\"
")
execute_process(COMMAND chmod +x "${ZIG_CC_WRAPPER}")

file(WRITE "${ZIG_AR_WRAPPER}" "#!/bin/sh
# Auto-generated by cmake/zig-cross.cmake -- do not edit
exec \"${ZIG_EXECUTABLE}\" ar \"$@\"
")
execute_process(COMMAND chmod +x "${ZIG_AR_WRAPPER}")

# ── Compiler configuration ───────────────────────────────────
set(CMAKE_C_COMPILER "${ZIG_CC_WRAPPER}")
set(CMAKE_C_COMPILER_ID "Clang")
set(CMAKE_C_COMPILER_FORCED TRUE)

set(CMAKE_AR "${ZIG_AR_WRAPPER}" CACHE FILEPATH "Archiver" FORCE)
set(CMAKE_RANLIB "true" CACHE FILEPATH "Ranlib (no-op for Zig)" FORCE)

# ── Static linking for musl targets ──────────────────────────
if(PARANOID_TARGET MATCHES "musl")
    set(CMAKE_EXE_LINKER_FLAGS_INIT "-static")
endif()

# ── Linker garbage-collection flag exported to top-level ─────
# Top-level CMakeLists reads PARANOID_LINKER_GC to pick the right
# dead-code-elimination flag for the active linker.

# ── Cross-compilation search paths ──────────────────────────
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Force the CLI-only branch in the top-level CMakeLists.
set(PARANOID_CROSS_CLI TRUE)

# Don't try_compile a real executable (would need a runner).
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
